// import { useContext } from "react";
// import {UserAnswersContext } from "../context/UserAnswersProvider"
import Head from "next/head";
import UserAnswerCard from "@/components/UserAnswerCarddeneme2";
// import { useRouter } from "next/router";

const Answers = () => {
  // const { userAnswers } = useContext(UserAnswersContext);
  // const router = useRouter();
  // const { query } = router;

  // console.log(query);
  // console.log(userAnswers);

  return (
    <>
      <Head>
        <title>Answers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <UserAnswerCard/>
      </div>
    </>
  );
};

export default Answers;
